
service: contactotron

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    CONTACT_TOPIC_ARN:
      Ref: contactotronTopic
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
      Resource:
        - Ref: contactotronTopic

package:
  exclude:
    - node_modules/**

functions:
  submitContactForm:
    handler: handler.submitContactForm
    events:
      - http:
          path: submitContactForm
          method: post
          cors: true

plugins:
  - serverless-finch

custom:
  client:
    bucketName: jerryhire8test1-lab-demo-2020
    distributionFolder: build/

resources:
  Resources:
    contactotronTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "Contactotron Contact Form"
        TopicName: contactotronTopic-${self:provider.stage}