
service: contactotron

provider:
  name: aws
  runtime: nodejs12.x

package:
  exclude:
    - node_modules/**

functions:
  submitContactForm:
    handler: handler.submitContactForm
    events:
      - http:
          path: submitContactForm
          method: post
          cors: true

plugins:
  - serverless-finch

custom:
  client:
    bucketName: jerryhire8test1-lab-demo-2020
    distributionFolder: build/