
service: contactotron

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    CONTACT_TOPIC_ARN:
      Ref: contactotronTopic
    CONTACT_TABLE_NAME:
      Ref: contactotronMessagesTable
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
      Resource:
        - Ref: contactotronTopic

    - Effect: 'Allow'
      Action:
        - "dynamodb:PutItem"
      Resource:
        Fn::GetAtt:
          - contactotronMessagesTable
          - Arn

package:
  exclude:
    - build/**
    - public/**
    - src/**
    - node_modules/**
  include:
    - node_modules/uuid/**

functions:
  submitContactForm:
    handler: handler.submitContactForm
    events:
      - http:
          path: submitContactForm
          method: post
          cors: true

  saveContactMessage:
    handler: handler.saveContactMessage
    events:
      - sns:
          arn:
            Ref: contactotronTopic
          topicName: contactotronTopic-${self:provider.stage}

plugins:
  - serverless-finch

custom:
  client:
    bucketName: jerryhire8test1-lab-demo-2020
    distributionFolder: build/

resources:
  Resources:
    contactotronTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "Contactotron Contact Form"
        TopicName: contactotronTopic-${self:provider.stage}

    contactotronMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

