
service: contactotron

provider:
  name: aws
  runtime: nodejs12.x

package:
  exclude:
    - node_modules/**

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-finch

custom:
  client:
    bucketName: jerryhire8test1-lab-demo-2020
    distributionFolder: build