service: gladnews

frameworkVersion: ">=1.9.0 <2.0.0"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10

custom:
  stage: ${opt:stage, self:provider.stage}
  
  
functions:
  presign:
    handler: backend/pre_signup.handler
  test:
    handler: backend/test_auth.handler
    events:
      - http:
          cors: true
          authorizer:
            name: pool_auth
            arn: '${self:custom.${self:custom.stage}CognitoPool}'
          path: /test
          method: get
  gql:
    handler: backend/gql_endpoint.handler
    events:
      - http:
          cors: true
          authorizer:
            name: pool_auth
            arn: '${self:custom.${self:custom.stage}CognitoPool}'
          path: /gql
          method: post

resources:
  Outputs:
    WebSiteUrl:
      Value: {"Fn::GetAtt": [WebSite, WebsiteURL]}
    WebSiteBucket:
      Value: {Ref: WebSite}
  Resources:
    WebSite:
      Type: "AWS::S3::Bucket"
      Properties:
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html
package:
  exclude:
    - bin/**
    - static/**
    - resources/**
    - package.json
    - package-lock.json
    - node_modules/**
  include:
    - node_modules/uuid/**
    - node_modules/lodash/**
    - node_modules/graphql/**
    - node_modules/iterall/**