service: urlshortener

frameworkVersion: ">=1.7.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    SLS_STAGE: ${opt:stage, self:provider.stage}

functions:
  main:
    handler: main/index.handler
    events:
      - http:
          path: /
          method: get
  create:
    handler: create/index.handler
    events:
      - http:
          path: /
          method: post
  redirect:
    handler: redirect/index.handler
    events:
      - http:
          path: /{slug}
          method: get
    environment:
      URL_INSTALL: https://serverless.com/framework/docs/providers/aws/guide/installation/
      URL_MAIN: https://serverless.com
