service: auth0-backend

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: src/helloWorld/handler.hello
    events:
      - http:
          method: get
          path: hello
          cors: true

  authorizer:
    handler: src/authorizer/handler.handler
    environment:
      AUTH0_DOMAIN: <AUTH0_DOMAIN>

