service:
  name: service-10-aws-stepfunction
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-step-functions
provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    

functions:
  hello:
    handler: handler.hello
  startExecution:
    handler: handler.startExecution
    environment:
      STEP_FUNCTION_ARN: ${self:resources.Outputs.myFirstStateMachine.Value}


stepFunctions:
  stateMachines:
    myFirstStateMachine:
      name: myFirstStateMachine
      events:
        - http:
            path: hello
            method: GET
      definition: 
        Comment: "MyFirst state machine"
        StartAt: WaitState
        States:
          WaitState:
            Type: Wait
            Seconds: 10
            Next: State1
          State1:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            End: true
          
resources:
  Outputs:
    myFirstStateMachine:
      Description: The ARN of the example state machine
      Value:
        Ref: MyFirstStateMachine